### ISSUE TITLE
RuntimeError: Distributed package doesn't have NCCL built in

### ISSUE THREAD

**Issue by manoj21192** [meta-llama/codellama#70]
When trying to run example_completion.py file in my windows laptop, I am getting below error:
![Error](https://github.com/facebookresearch/codellama/assets/52530801/0b8d0d51-be1f-4178-a089-cf4676aa6654)

I am using pytorch 2.0 version with CUDA 11.7 . On typing the command
import torch.distributed as dist

if dist.is_nccl_available():
    print("NCCL is available and built into PyTorch.")
else:
    print("NCCL is not available in this PyTorch installation.")
 
 I am getting the output "NCCL is not available in this PyTorch installation."
 What should I do ?

**Comment by GaganHonor** [comment]
Based on the error message you provided, it seems that you are encountering a ChildFailedError when trying to run the example_completion.py file in your Windows laptop. This error is related to distributed training in PyTorch.

To fix this issue, you can try the following steps:

Check PyTorch Documentation: Visit the PyTorch documentation page on elastic errors to enable traceback and get more information about the error.

Update PyTorch and CUDA Versions: Make sure you are using compatible versions of PyTorch and CUDA. It is recommended to use the latest stable versions to ensure compatibility and access to the latest

**Comment by manoj21192** [comment]
Everything checked but unable to resolve. I am using latest version of Pytorch and 11.7 CUDA.

**Comment by srinivaskumarramdas** [comment]
Getting the same error on my macbook as well.

**Comment by GaganHonor** [comment]
please try to explain more  and share information like system info , and all logs in txt form or link to them

**Comment by manoj21192** [comment]
As of now, for 7B parameter model, its working on windows by making changes to generator.py file by using torch.distributed.init_process_group("gloo"), instead of "nccl". 
Is this methodology fine if I want to use high parameter model in future?

**Comment by srinivaskumarramdas** [comment]
"gloo" worked on Apple M2 chips mac as well. had some more additional changes covered in this PR: https://github.com/facebookresearch/codellama/pull/18 .

**Comment by GaganHonor** [comment]
Please close this issue if issue is Fixed 
![RunForrestPuppetGIF](https://github.com/facebookresearch/codellama/assets/141204441/e67b8bbc-706b-424f-95c3-bd4cae40dcbc)

**Comment by manoj21192** [comment]
Use gloo to make it work on Windows
